function [E,gE] = modelF(x,sim,data,roi,noiseLevel,beta,filterCutoffs,...
    limitVector)
noMod = true;
[noise,rho,delta,epsilon,omega,theta,fwhm] = ...
    vectorToParameters(x,sim,noMod);
if nargout==2
    [~,~,E,dE_dNoise,dE_dRho,dE_dDelta,dE_dEpsilon,dE_dTheta,dE_dOmega,...
        dE_dFwhm] = computeODCModel(sim,...
        noise,rho,delta,epsilon,theta,omega,beta,fwhm,...
        data,noiseLevel,roi,filterCutoffs,limitVector);
    gE =  parametersToVector(dE_dNoise,dE_dRho,dE_dDelta,...
        dE_dEpsilon,dE_dOmega,dE_dTheta,dE_dFwhm);
else
    [~,~,E] = computeODCModel(sim,noise,rho,delta,epsilon,theta,omega,...
        beta,fwhm,data,noiseLevel,roi,filterCutoffs,limitVector);
end
end
