function [E,gE] = modelFSimultaneous(...
    x,sim,dataGE,dataSE,roiGE,roiSE,noiseLevelGE,noiseLevelSE,...
    betaGE,betaSE,filterCutoffsGE,filterCutoffsSE,limitVector)
noMod = true;
[noise,rho,delta,epsilon,omega,theta,fwhmGE,fwhmSE] = ...
    vectorToParametersSimultaneous(x,sim,noMod);
if nargout==2
    [~,~,~,E,dE_dNoise,dE_dRho,dE_dDelta,dE_dEpsilon,dE_dTheta,dE_dOmega,...
        dE_dFwhmGE,dE_dFwhmSE] = computeODCModelSimultaneous(sim,...
        noise,rho,delta,epsilon,theta,omega,betaGE,betaSE,fwhmGE,fwhmSE,...
        dataGE,dataSE,noiseLevelGE,noiseLevelSE,roiGE,roiSE,...
        filterCutoffsGE,filterCutoffsSE,limitVector);
    gE =  parametersToVectorSimultaneous(dE_dNoise,dE_dRho,dE_dDelta,...
        dE_dEpsilon,dE_dOmega,dE_dTheta,dE_dFwhmGE,dE_dFwhmSE);
else
    [~,~,~,E] = computeODCModelSimultaneous(sim,noise,rho,delta,epsilon,...
        theta,omega,betaGE,betaSE,fwhmGE,fwhmSE,dataGE,dataSE,...
        noiseLevelGE,noiseLevelSE,roiGE,roiSE,...
        filterCutoffsGE,filterCutoffsSE,limitVector);
end
end
